#!/usr/bin/env bash
# Build the wave-mcp-viewer-assets package (Surfer WASM + surver binary).
#
# The viewer assets are EUPL-1.2 (Surfer project); they are distributed as
# a SEPARATE package so the MIT core stays license-clean. This script
# packs an sdist/wheel from a prepared asset directory and embeds the
# EUPL-1.2 license text plus a provenance NOTICE (see docs/licenses/).
#
# Usage:
#   deploy/build_viewer_assets.sh <asset_dir> [version]
#
# <asset_dir> layout (validated):
#   surver            executable, ideally the musl static build
#   wasm/index.html   Surfer WASM bundle (CI job pages_build, or self-built;
#                     wellen version MUST match the surver binary)
#
# Version pairing rule: WASM and surver must come from the SAME Surfer
# build. Mixed wellen versions are rejected at connect time by Surfer.
set -euo pipefail

ASSET_DIR=${1:?usage: build_viewer_assets.sh <asset_dir> [version]}
VERSION=${2:-0.7.0}
HERE=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$HERE/.." && pwd)
OUT="$HERE/viewer-assets-build"

[[ -f "$ASSET_DIR/surver" ]] || { echo "missing $ASSET_DIR/surver"; exit 1; }
[[ -f "$ASSET_DIR/wasm/index.html" ]] || { echo "missing $ASSET_DIR/wasm/index.html"; exit 1; }

# surfer's own service worker must not be shipped: wave-mcp serves its own
# sw.js (header restore + version handshake) from the shell directory.
rm -rf "$OUT"
PKG="$OUT/wave_mcp_viewer_assets"
mkdir -p "$PKG/data/wasm"
cp "$ASSET_DIR/surver" "$PKG/data/surver"
chmod +x "$PKG/data/surver"
cp -r "$ASSET_DIR/wasm/." "$PKG/data/wasm/"
rm -f "$PKG/data/wasm/sw.js" "$PKG/data/wasm/sw_new.js" \
      "$PKG/data/wasm/sw.js.orig" "$PKG/data/wasm/view.html" \
      "$PKG/data/wasm"/*.vcd "$PKG/data/wasm"/*.fst 2>/dev/null || true

cat > "$PKG/__init__.py" <<'EOF'
"""Viewer assets for wave-mcp (Surfer WASM + surver). EUPL-1.2.

Data files live in the ``data/`` subdirectory; wave_mcp.viewer discovers
them via this package. See THIRD_PARTY notes in the wave-mcp repository.
"""
EOF

# EUPL-1.2 requires every copy to carry the license text. Vendor the official
# text from docs/licenses/ into the package (see docs/licenses/README.md).
LICENSE_SRC="$REPO_ROOT"/docs/licenses/EUPL-1.2.txt
if [[ -f "$LICENSE_SRC" ]]; then
  cp "$LICENSE_SRC" "$OUT/LICENSE-EUPL-1.2.txt"
  cp "$LICENSE_SRC" "$PKG/LICENSE-EUPL-1.2.txt"
else
  echo "ERROR: $LICENSE_SRC not found; refusing to build an EUPL package"
  echo "       without the license text. See docs/licenses/README.md."
  exit 1
fi

# NOTICE: record the exact upstream provenance as EUPL art. 5 requires
# (source availability; sources are unmodified, so pointing at the pinned
# upstream ref is sufficient).
SURFER_REF=${SURFER_REF:-v0.7.0}
cat > "$OUT/NOTICE" <<EOF
wave-mcp-viewer-assets
======================

This package redistributes unmodified build artifacts of the Surfer
project (https://gitlab.com/surfer-project/surfer), licensed under the
European Union Public Licence v1.2 (EUPL-1.2):

  - surver binary: built from Surfer git ref ${SURFER_REF}
    (deploy/build_surver_static.sh records the build recipe)
  - wasm/ bundle: Surfer WASM build matching the same ref

The Surfer sources are NOT modified by wave-mcp; the exact upstream
source for this ref is available at:

  https://gitlab.com/surfer-project/surfer/-/tree/${SURFER_REF}

The full EUPL-1.2 text ships in this package as LICENSE-EUPL-1.2.txt.
wave-mcp itself (the consuming project) is MIT licensed and does not
link against these components; surver runs as a separate subprocess
and the WASM bundle is served as static files to the user's browser.
EOF
cp "$OUT/NOTICE" "$PKG/NOTICE"

# Optional: per-crate license report generated by deploy/build_surver_static.sh
# (cargo registry scan). Shipped alongside the binary when present.
CRATE_REPORT="$ASSET_DIR/surver-crate-licenses.txt"
if [[ -f "$CRATE_REPORT" ]]; then
  cp "$CRATE_REPORT" "$PKG/surver-crate-licenses.txt"
fi
if [[ -d "$ASSET_DIR/crates-license-files" ]]; then
  mkdir -p "$PKG/crates-license-files"
  cp "$ASSET_DIR"/crates-license-files/*.txt "$PKG/crates-license-files/" 2>/dev/null || true
fi

cat > "$OUT/pyproject.toml" <<EOF
[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "wave-mcp-viewer-assets"
version = "$VERSION"
description = "Waveform viewer assets (Surfer WASM + surver) for wave-mcp"
license = { text = "EUPL-1.2" }
requires-python = ">=3.10"

[tool.setuptools]
packages = ["wave_mcp_viewer_assets"]
license-files = ["LICENSE-EUPL-1.2.txt"]

[tool.setuptools.package-data]
wave_mcp_viewer_assets = [
    "data/surver",
    "data/wasm/**",
    "LICENSE-EUPL-1.2.txt",
    "NOTICE",
    "surver-crate-licenses.txt",
    "crates-license-files/**",
]
EOF

cat > "$OUT/README.md" <<'EOF'
# wave-mcp-viewer-assets

Prebuilt Surfer WASM bundle + surver binary consumed by `wave-mcp`'s
viewer (`wave-view`, `open_wave_view`). Licensed EUPL-1.2 (Surfer
project); distributed separately from the MIT-licensed wave-mcp core.

The full EUPL-1.2 license text and a provenance NOTICE ship with this
package (`LICENSE-EUPL-1.2.txt`, `NOTICE`). The Surfer sources are
unmodified; see the NOTICE for the exact upstream ref and repository.

Install together with the core:

    pip install wave-mcp[viewer]
EOF

( cd "$OUT" && python3 -m pip wheel --no-deps -w dist . >/dev/null )
echo "built:"
ls -la "$OUT/dist/"
echo
echo "install locally:  pip install $OUT/dist/*.whl"
echo "offline bundle:   copy the wheel into the bundle's wheels/ dir"
